[project]
name = "aoc24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
